### ISSUE TITLE
Remove css rule to prevent thick border

### ISSUE THREAD

**Issue by gmclelland** [adrianbj/ModuleSettingsImportExport#1]
Would you consider removing the css rule:

```css
#ModuleSettingsImportExport {
    position: relative;
    top: -2px;
}
```
I think it causes the following in the new admin theme uikit.

![modules processwire pwoliver test 2017-10-01 10-46-54](https://user-images.githubusercontent.com/40570/31056367-0bb724de-a696-11e7-9da4-bf8012dea4a0.jpg)

Hope that helps
